'use client';

import { Fragment } from 'react';

interface DisclaimerBannerProps {
  dismissible?: boolean;
  onDismiss?: () => void;
  dismissed?: boolean;
  persistent?: boolean;
}

const DISCLAIMER_TEXT = (
  <>
    <strong>Important: </strong>
    This platform provides general legal information only and does not constitute legal advice.
    The information is generated by AI and may contain inaccuracies.
    For legal matters that could significantly affect your rights, liberty, or finances,
    please consult with a qualified attorney licensed in your jurisdiction.
    No attorney-client relationship is created by using this service.
  </>
);

const SHORT_DISCLAIMER = (
  <>
    This platform provides <strong>general legal information only</strong> — not legal advice. 
    AI-generated content may contain inaccuracies. Consult a qualified attorney for matters affecting your rights, liberty, or finances.
  </>
);

export function DisclaimerBanner({ 
  dismissible = true, 
  onDismiss, 
  dismissed = false, 
  persistent = false 
}: DisclaimerBannerProps) {
  if (dismissed && dismissible && !persistent) return null;

  return (
      <div
        role="alert"
        aria-live="assertive"
        className={`
          relative p-5 bg-amber-50 border border-amber-200 rounded-xl
          ${dismissible ? 'pr-12' : ''}
          ${persistent ? 'mb-6' : 'mb-4'}
          transition-all duration-200
        `}
      >
        <div className="flex items-start gap-3">
          <svg
            className="flex-shrink-0 mt-0.5 h-5 w-5 text-amber-600 flex-shrink-0"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
          </svg>
          <div className="flex-1 min-w-0">
            {persistent ? (
              <p className="text-sm text-amber-800">{SHORT_DISCLAIMER}</p>
            ) : (
              <p className="text-sm text-amber-800">{DISCLAIMER_TEXT}</p>
            )}
          </div>
          {dismissible && onDismiss && (
            <button
              type="button"
              onClick={onDismiss}
              className="flex-shrink-0 p-1.5 text-amber-600 hover:text-amber-800 focus:outline-none focus:ring-2 focus:ring-amber-500 focus:ring-offset-2 focus:ring-offset-amber-50 rounded-lg"
              aria-label="Dismiss disclaimer"
            >
              <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" />
              </svg>
            </button>
          )}
        </div>
      </div>
  );
}

export function PersistentDisclaimer() {
  return <DisclaimerBanner persistent dismissible={false} />;
}