import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, List, Optional, Set, NamedTuple
from urllib.parse import urlparse

from app.models.schemas import (
    Jurisdiction, SourceType, Source, LegalCategory, RiskLevel,
    RequestType, ClarificationQuestion, TerminologyExplanation,
    DocumentChecklistItem, FollowUpSuggestion, QuestionQuality,
    CoverageLevel
)

logger = logging.getLogger(__name__)


# Source database (in production, this would connect to a real legal database)
VERIFIED_SOURCES = {
    Jurisdiction.US_FEDERAL: [
        Source(
            type=SourceType.STATUTE,
            title="Fair Housing Act",
            citation="42 U.S.C. §§ 3601-3619",
            url="https://www.justice.gov/crt/fair-housing-act-1",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
        Source(
            type=SourceType.STATUTE,
            title="Family and Medical Leave Act",
            citation="29 U.S.C. §§ 2601-2654",
            url="https://www.dol.gov/agencies/whd/fmla",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
        Source(
            type=SourceType.STATUTE,
            title="Americans with Disabilities Act",
            citation="42 U.S.C. §§ 12101-12213",
            url="https://www.ada.gov/",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
    ],
    Jurisdiction.US_CA: [
        Source(
            type=SourceType.STATUTE,
            title="California Tenant Protection Act",
            citation="Cal. Civ. Code §§ 1946.2, 1947.12",
            url="https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CIV&division=3.&title=5.&part=4.&chapter=2.&article=2.",
            jurisdiction=Jurisdiction.US_CA,
            verified=True
        ),
        Source(
            type=SourceType.GOVERNMENT_PUBLICATION,
            title="California Courts Self-Help Guide",
            url="https://selfhelp.courts.ca.gov/",
            jurisdiction=Jurisdiction.US_CA,
            verified=True
        ),
    ],
}


DISCLAIMER = (
    "DISCLAIMER\n\n"
    "This platform provides general legal information only and does not constitute legal advice. "
    "The information provided is generated by AI and may contain inaccuracies. "
    "For legal matters that could significantly affect your rights, liberty, or finances, "
    "please consult with a qualified attorney licensed in your jurisdiction. "
    "No attorney-client relationship is created by using this service."
)


# High-risk keywords that trigger escalation
HIGH_RISK_KEYWORDS = {
    RiskLevel.CRITICAL: [
        "arrest", "detention", "deportation", "eviction notice", "foreclosure",
        "domestic violence", "restraining order", "child custody emergency",
        "suicide", "self-harm", "imminent danger", "warrant", "subpoena",
        "court date tomorrow", "deadline today", "deadline tomorrow"
    ],
    RiskLevel.HIGH: [
        "lawsuit", "criminal charge", "divorce", "custody battle",
        "discrimination", "harassment", "wrongful termination",
        "medical malpractice", "personal injury", "statute of limitations",
        "immigration court", "asylum", "visa denial"
    ],
    RiskLevel.MEDIUM: [
        "contract dispute", "landlord tenant", "wage theft", "overtime",
        "unemployment benefits", "social security denial", "medicaid",
        "special education", "IEP", "consumer fraud", "debt collection"
    ]
}


# Request type classification patterns
REQUEST_TYPE_PATTERNS = {
    RequestType.DEADLINE_INQUIRY: [
        r"deadline", r"statute of limitations", r"time limit", r"how long do i have",
        r"when must i", r"filing deadline", r"appeal deadline"
    ],
    RequestType.PROCEDURAL_GUIDANCE: [
        r"how do i file", r"how to file", r"steps to", r"process for",
        r"procedure to", r"what forms", r"where do i file"
    ],
    RequestType.RIGHTS_EXPLANATION: [
        r"what are my rights", r"am i entitled", r"do i have a right",
        r"what protections", r"legal rights", r"employee rights", r"tenant rights"
    ],
    RequestType.FORM_ASSISTANCE: [
        r"fill out", r"complete the form", r"form ", r"application for",
        r"petition for", r"motion for"
    ],
    RequestType.DOCUMENT_REVIEW: [
        r"review this", r"look at this document", r"analyze this",
        r"what does this mean", r"interpret this"
    ],
}


# Legal category patterns
LEGAL_CATEGORY_PATTERNS = {
    LegalCategory.HOUSING: [
        r"eviction", r"landlord", r"tenant", r"rent", r"lease", r"housing",
        r"foreclosure", r"mortgage", r"habitability", r"security deposit"
    ],
    LegalCategory.EMPLOYMENT: [
        r"employer", r"employee", r"workplace", r"fired", r"terminated",
        r"discrimination", r"harassment", r"wage", r"overtime", r"unemployment",
        r"workers compensation", r"FMLA", r"ADA", r"wrongful termination"
    ],
    LegalCategory.FAMILY: [
        r"divorce", r"custody", r"child support", r"alimony", r"spousal support",
        r"adoption", r"guardianship", r"domestic violence", r"restraining order",
        r"paternity", r"visitation"
    ],
    LegalCategory.CRIMINAL: [
        r"arrest", r"charge", r"criminal", r"misdemeanor", r"felony",
        r"DUI", r"DWI", r"probation", r"parole", r"public defender",
        r"miranda", r"search warrant", r"indictment"
    ],
    LegalCategory.IMMIGRATION: [
        r"immigration", r"visa", r"green card", r"citizenship", r"asylum",
        r"deportation", r"removal", r"ICE", r"USCIS", r"DACA", r"TPS"
    ],
    LegalCategory.CONSUMER: [
        r"consumer", r"fraud", r"scam", r"debt collection", r"credit report",
        r"identity theft", r"warranty", r"lemon law", r"false advertising"
    ],
    LegalCategory.CIVIL_RIGHTS: [
        r"civil rights", r"discrimination", r"police misconduct", r"excessive force",
        r"voting rights", r"ADA", r"disability rights", r"housing discrimination"
    ],
    LegalCategory.HEALTHCARE: [
        r"medical", r"healthcare", r"insurance", r"medicaid", r"medicare",
        r"HIPAA", r"medical malpractice", r"informed consent", r"patient rights"
    ],
    LegalCategory.EDUCATION: [
        r"education", r"school", r"IEP", r"special education", r"504 plan",
        r"student rights", r"discipline", r"expulsion", r"Title IX"
    ],
    LegalCategory.FINANCIAL: [
        r"bankruptcy", r"debt", r"credit", r"loan", r"foreclosure",
        r"repossession", r"garnishment", r"tax", r"IRS"
    ],
}


# Jurisdiction detection patterns
JURISDICTION_PATTERNS = {
    Jurisdiction.US_CA: [r"california", r"\bca\b", r"cal\."],
    Jurisdiction.US_NY: [r"new york", r"\bny\b", r"n\.y\."],
    Jurisdiction.US_TX: [r"texas", r"\btx\b", r"tx\."],
    Jurisdiction.UK: [r"united kingdom", r"\buk\b", r"england", r"wales", r"scotland"],
    Jurisdiction.CA_FEDERAL: [r"canada", r"federal canada"],
    Jurisdiction.CA_ON: [r"ontario", r"\bon\b", r"on\."],
    Jurisdiction.AU_FEDERAL: [r"australia", r"commonwealth"],
    Jurisdiction.EU: [r"european union", r"\beu\b", r"gdpr"],
}


import re
from typing import List, Dict, Any, Optional
from datetime import datetime


# Legal terminology explanations
LEGAL_TERMINOLOGY = {
    "eviction": TerminologyExplanation(
        term="Eviction",
        explanation="A court-ordered process that removes a tenant from a rental property. The specific rules, notice periods, and procedures vary significantly by jurisdiction and reason.",
        category="housing"
    ),
    "retaliation": TerminologyExplanation(
        term="Retaliation",
        explanation="A general legal concept describing adverse action allegedly taken in response to a protected activity (such as filing a complaint). Whether a specific situation qualifies depends on applicable law and facts.",
        category="general"
    ),
    "landlord-tenant": TerminologyExplanation(
        term="Landlord-Tenant Law",
        explanation="The body of law governing the rights and responsibilities of property owners (landlords) and renters (tenants). It covers topics like rent, deposits, repairs, and eviction procedures.",
        category="housing"
    ),
    "wrongful termination": TerminologyExplanation(
        term="Wrongful Termination",
        explanation="A legal concept describing termination of employment that violates statutory protections, contractual agreements, or public policy. Whether a termination qualifies depends on jurisdiction and specific circumstances.",
        category="employment"
    ),
    "discrimination": TerminologyExplanation(
        term="Discrimination",
        explanation="A general legal concept describing unfair treatment of a person based on a protected characteristic (such as race, gender, disability, or religion). Laws vary by jurisdiction and context.",
        category="general"
    ),
    "statute of limitations": TerminologyExplanation(
        term="Statute of Limitations",
        explanation="A law that sets the maximum time after an event within which legal proceedings may be initiated. The specific time limits vary by legal matter type and jurisdiction.",
        category="general"
    ),
    "custody": TerminologyExplanation(
        term="Custody",
        explanation="A legal concept relating to the care and decision-making rights for a child. Legal custody and physical custody are distinct concepts, and rules vary significantly by jurisdiction.",
        category="family"
    ),
    "immigration": TerminologyExplanation(
        term="Immigration",
        explanation="The legal process of entering and remaining in a country other than one's own. Immigration law is complex and involves federal agencies, courts, and specific procedures that vary by case type.",
        category="immigration"
    ),
}

# Unified question analysis - scans question once, computes all classifications
class QuestionAnalysis(NamedTuple):
    """Unified question analysis result to avoid repeated scanning."""
    question_lower: str
    request_type: RequestType
    legal_category: LegalCategory
    jurisdiction: Jurisdiction
    risk_level: RiskLevel
    quality: QuestionQuality
    terminology_explanations: List[TerminologyExplanation]
    document_checklist: List[DocumentChecklistItem]
    follow_up_suggestions: List[FollowUpSuggestion]
    clarification_questions: List[ClarificationQuestion]
    sources: List[Source]
    information_coverage: CoverageLevel
    coverage_reason: str


def analyze_question_unified(
    question: str,
    context: Optional[str] = None,
    jurisdiction_hint: Optional[Jurisdiction] = None,
) -> QuestionAnalysis:
    """
    Unified question analysis - scans question once and computes all classifications.
    This avoids repeated regex scanning across multiple functions.
    """
    question_lower = question.strip().lower()
    text_with_context = question_lower + " " + (context or "").lower()
    
    # Single pass: classify request type
    request_type = RequestType.GENERAL_INFO
    for req_type, patterns in REQUEST_TYPE_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, question_lower):
                request_type = req_type
                break
        if request_type != RequestType.GENERAL_INFO:
            break
    
    # Single pass: classify legal category
    scores = {}
    for category, patterns in LEGAL_CATEGORY_PATTERNS.items():
        score = sum(1 for pattern in patterns if re.search(pattern, question_lower))
        if score > 0:
            scores[category] = score
    legal_category = max(scores, key=scores.get) if scores else LegalCategory.OTHER
    
    # Detect jurisdiction
    if jurisdiction_hint and jurisdiction_hint != Jurisdiction.UNKNOWN:
        jurisdiction = jurisdiction_hint
    else:
        jurisdiction = Jurisdiction.UNKNOWN
        for jur, patterns in JURISDICTION_PATTERNS.items():
            for pattern in patterns:
                if re.search(pattern, question_lower + " " + (context or "").lower()):
                    jurisdiction = jur
                    break
            if jurisdiction != Jurisdiction.UNKNOWN:
                break
    
    # Risk assessment
    risk_level = RiskLevel.LOW
    for keyword in HIGH_RISK_KEYWORDS[RiskLevel.CRITICAL]:
        if keyword in question_lower:
            risk_level = RiskLevel.CRITICAL
            break
    if risk_level != RiskLevel.CRITICAL:
        for keyword in HIGH_RISK_KEYWORDS[RiskLevel.HIGH]:
            if keyword in question_lower:
                risk_level = RiskLevel.HIGH
                break
    if risk_level not in (RiskLevel.CRITICAL, RiskLevel.HIGH):
        for keyword in HIGH_RISK_KEYWORDS[RiskLevel.MEDIUM]:
            if keyword in question_lower:
                risk_level = RiskLevel.MEDIUM
                break
    if risk_level == RiskLevel.LOW:
        if legal_category in [LegalCategory.CRIMINAL, LegalCategory.IMMIGRATION]:
            risk_level = RiskLevel.HIGH
    
    # Source retrieval (early, reused by coverage)
    sources = []
    if jurisdiction in VERIFIED_SOURCES:
        sources.extend(VERIFIED_SOURCES[jurisdiction])
    if jurisdiction in [Jurisdiction.US_CA, Jurisdiction.US_NY, Jurisdiction.US_TX]:
        sources.extend(VERIFIED_SOURCES.get(Jurisdiction.US_FEDERAL, []))
    sources = sources[:5]
    
    # Question quality
    missing = []
    if jurisdiction == Jurisdiction.UNKNOWN:
        missing.append("jurisdiction (state/country)")
    words = question_lower.split()
    if len(words) < 5:
        missing.append("specific details about the situation")
    if legal_category == LegalCategory.HOUSING and "eviction" in question_lower:
        if "written" not in question_lower and "notice" not in question_lower:
            missing.append("whether a written notice was received")
    if legal_category == LegalCategory.EMPLOYMENT and "terminat" in question_lower:
        if "employer size" not in question_lower:
            missing.append("employer size and tenure details")
    score = max(0, 100 - (len(missing) * 25))
    level = "complete" if score >= 75 else ("partial" if score >= 50 else "needs_more_context")
    quality = QuestionQuality(
        score=score, level=level, missing_information=missing, is_complete=(score >= 75)
    )
    
    # Terminology explanations
    terminology_explanations = [
        explanation for term, explanation in LEGAL_TERMINOLOGY.items()
        if term.lower() in question_lower
    ]
    
    # Document checklist
    category_key = legal_category.value
    if category_key in DOCUMENT_CHECKLISTS:
        document_checklist = DOCUMENT_CHECKLISTS[category_key]
    else:
        document_checklist = [
            DocumentChecklistItem(item="Relevant documents related to the matter", category=category_key),
            DocumentChecklistItem(item="Correspondence or communications", category=category_key),
            DocumentChecklistItem(item="Records and supporting evidence", category=category_key),
        ]
    
    # Follow-up suggestions
    if category_key in FOLLOW_UP_TEMPLATES:
        follow_up_suggestions = FOLLOW_UP_TEMPLATES[category_key]
    else:
        follow_up_suggestions = [
            FollowUpSuggestion(question="What if I received a written notice?", reason="Understanding the notice type helps clarify your rights", category="general"),
            FollowUpSuggestion(question="What documents should I keep?", reason="Document preservation is important", category="general"),
            FollowUpSuggestion(question="What information should I gather for a lawyer?", reason="Being organized helps legal professionals assess your situation", category="general"),
        ]
    
    # Clarification questions
    clarification_questions = []
    if jurisdiction == Jurisdiction.UNKNOWN:
        clarification_questions.append(ClarificationQuestion(
            question="What is your location (state/country)? Legal information varies significantly by jurisdiction.",
            reason="Jurisdiction is required for accurate legal information", required=True
        ))
    if request_type == RequestType.DEADLINE_INQUIRY:
        clarification_questions.append(ClarificationQuestion(
            question="When did the event or incident occur? This helps determine applicable deadlines.",
            reason="Deadlines depend on specific dates", required=True
        ))
    if legal_category == LegalCategory.HOUSING and "eviction" in question_lower:
        clarification_questions.append(ClarificationQuestion(
            question="Have you received a written eviction notice? If so, what type (e.g., 3-day, 30-day)?",
            reason="Eviction procedures vary by notice type", required=True
        ))
    if legal_category == LegalCategory.EMPLOYMENT and "terminat" in question_lower:
        clarification_questions.append(ClarificationQuestion(
            question="How many employees does your employer have? This affects which laws apply.",
            reason="Employment law thresholds vary by employer size", required=False
        ))
    
    # Information coverage
    if jurisdiction == Jurisdiction.UNKNOWN:
        information_coverage = CoverageLevel.LIMITED
        coverage_reason = "The question does not specify a jurisdiction. Source coverage may be limited."
    elif not sources:
        information_coverage = CoverageLevel.LIMITED
        coverage_reason = "No verified sources are available for this topic in the detected jurisdiction."
    elif jurisdiction in [Jurisdiction.US_CA, Jurisdiction.US_NY, Jurisdiction.US_TX]:
        if len(sources) >= 3:
            information_coverage = CoverageLevel.HIGH
            coverage_reason = "Good source coverage: both federal and state sources available."
        else:
            information_coverage = CoverageLevel.MODERATE
            coverage_reason = "Some source coverage available, but may be limited."
    elif jurisdiction == Jurisdiction.US_FEDERAL:
        information_coverage = CoverageLevel.MODERATE
        coverage_reason = "Federal source coverage available. State-specific details may be limited."
    else:
        information_coverage = CoverageLevel.LIMITED
        coverage_reason = "Verified curated source coverage is currently limited for this jurisdiction."
    
    # Terminology explanations (reused)
    terminology_explanations = [
        explanation for term, explanation in LEGAL_TERMINOLOGY.items()
        if term.lower() in question_lower
    ]
    
    return QuestionAnalysis(
        question_lower=question_lower,
        request_type=request_type,
        legal_category=legal_category,
        jurisdiction=jurisdiction,
        risk_level=risk_level,
        quality=quality,
        terminology_explanations=terminology_explanations,
        document_checklist=document_checklist,
        follow_up_suggestions=follow_up_suggestions,
        clarification_questions=clarification_questions,
        sources=sources,
        information_coverage=information_coverage,
        coverage_reason=coverage_reason,
    )


# Document checklists by category
DOCUMENT_CHECKLISTS = {
    "housing": [
        DocumentChecklistItem(item="Lease/rental agreement", category="housing"),
        DocumentChecklistItem(item="Any notices received (written or electronic)", category="housing"),
        DocumentChecklistItem(item="Communications with landlord (emails, texts, letters)", category="housing"),
        DocumentChecklistItem(item="Payment records (receipts, bank statements)", category="housing"),
        DocumentChecklistItem(item="Photographs of conditions (if applicable)", category="housing"),
        DocumentChecklistItem(item="Homeowner/renter insurance policy", category="housing"),
    ],
    "employment": [
        DocumentChecklistItem(item="Employment agreement or contract", category="employment"),
        DocumentChecklistItem(item="Offer letter or job description", category="employment"),
        DocumentChecklistItem(item="Relevant communications (emails, memos)", category="employment"),
        DocumentChecklistItem(item="Payslips or payroll records", category="employment"),
        DocumentChecklistItem(item="Workplace policies or employee handbook", category="employment"),
        DocumentChecklistItem(item="Time records or schedules", category="employment"),
    ],
    "consumer": [
        DocumentChecklistItem(item="Receipt or invoice", category="consumer"),
        DocumentChecklistItem(item="Warranty or guarantee documentation", category="consumer"),
        DocumentChecklistItem(item="Correspondence with seller/lender", category="consumer"),
        DocumentChecklistItem(item="Photographs of product/condition", category="consumer"),
        DocumentChecklistItem(item="Credit report or account statements", category="consumer"),
    ],
    "family": [
        DocumentChecklistItem(item="Marriage or divorce decree", category="family"),
        DocumentChecklistItem(item="Child custody or support orders", category="family"),
        DocumentChecklistItem(item="Financial records and assets", category="family"),
        DocumentChecklistItem(item="Communication records with other party", category="family"),
    ],
    "criminal": [
        DocumentChecklistItem(item="Any court documents or notices", category="criminal"),
        DocumentChecklistItem(item="Arrest or charge records", category="criminal"),
        DocumentChecklistItem(item="Communication with legal counsel", category="criminal"),
    ],
}

# Follow-up suggestion templates
FOLLOW_UP_TEMPLATES = {
    "housing": [
        FollowUpSuggestion(question="What if I received a written notice?", reason="Understanding the notice type helps clarify your rights and timeline", category="housing"),
        FollowUpSuggestion(question="What documents should I keep?", reason="Document preservation is important for any housing dispute", category="housing"),
        FollowUpSuggestion(question="What information should I gather for a lawyer?", reason="Being organized helps legal professionals assess your situation", category="housing"),
    ],
    "employment": [
        FollowUpSuggestion(question="What if I received a written notice?", reason="Understanding the notice type helps clarify your rights and timeline", category="employment"),
        FollowUpSuggestion(question="What documents should I keep?", reason="Document preservation is important for any employment dispute", category="employment"),
        FollowUpSuggestion(question="What information should I gather for a lawyer?", reason="Being organized helps legal professionals assess your situation", category="employment"),
    ],
    "consumer": [
        FollowUpSuggestion(question="What does the warranty cover?", reason="Warranty terms vary by product and seller", category="consumer"),
        FollowUpSuggestion(question="How do I file a complaint with the agency?", reason="Government agencies often have specific complaint procedures", category="consumer"),
    ],
    "family": [
        FollowUpSuggestion(question="What if I received a written notice?", reason="Understanding the notice type helps clarify your rights and timeline", category="family"),
        FollowUpSuggestion(question="What documents should I keep?", reason="Document preservation is important for any family law matter", category="family"),
    ],
    "criminal": [
        FollowUpSuggestion(question="What should I do before speaking to anyone?", reason="You may want to consult with a qualified attorney first", category="criminal"),
        FollowUpSuggestion(question="What documents should I keep?", reason="Document preservation is important for any criminal matter", category="criminal"),
    ],
}

# Question quality analysis patterns
QUESTION_QUALITY_PATTERNS = {
    "missing_jurisdiction": {
        "pattern": r"^.*\b(what|how|can|should|do i|does|is it|my)\b.*$",
        "reason": "No jurisdiction specified. Legal information varies significantly by location."
    },
    "missing_details": {
        "pattern": r"^(can my|could my|should i|what if|will my|does my)\b.*\?",
        "reason": "The question may benefit from additional context about the specific situation."
    },
}


def analyze_question_quality(question: str, legal_category: LegalCategory, jurisdiction: Jurisdiction) -> QuestionQuality:
    """Analyze whether a question contains enough information for a useful response."""
    question_lower = question.strip().lower()
    missing = []

    # Check jurisdiction
    if jurisdiction == Jurisdiction.UNKNOWN:
        missing.append("jurisdiction (state/country)")

    # Check if question is very short
    words = question_lower.split()
    if len(words) < 5:
        missing.append("specific details about the situation")

    # Check for common missing elements by category
    if legal_category == LegalCategory.HOUSING and "eviction" in question_lower:
        if "written" not in question_lower and "notice" not in question_lower:
            missing.append("whether a written notice was received")

    if legal_category == LegalCategory.EMPLOYMENT and "terminat" in question_lower:
        if "employer size" not in question_lower:
            missing.append("employer size and tenure details")

    score = 100 - (len(missing) * 25)
    level = "complete" if score >= 75 else ("partial" if score >= 50 else "needs_more_context")

    return QuestionQuality(
        score=max(score, 0),
        level=level,
        missing_information=missing,
        is_complete=(score >= 75)
    )


def assess_information_coverage(
    question: str,
    jurisdiction: Jurisdiction,
    sources: List[Source],
    legal_category: LegalCategory
) -> tuple[CoverageLevel, str]:
    """Assess how much information coverage is available for a question."""
    if jurisdiction == Jurisdiction.UNKNOWN:
        return CoverageLevel.LIMITED, "The question does not specify a jurisdiction. Source coverage may be limited."

    if not sources:
        return CoverageLevel.LIMITED, "No verified sources are available for this topic in the detected jurisdiction."

    if jurisdiction in [Jurisdiction.US_CA, Jurisdiction.US_NY, Jurisdiction.US_TX]:
        if len(sources) >= 3:
            return CoverageLevel.HIGH, "Good source coverage: both federal and state sources available."
        return CoverageLevel.MODERATE, "Some source coverage available, but may be limited."

    if jurisdiction == Jurisdiction.US_FEDERAL:
        return CoverageLevel.MODERATE, "Federal source coverage available. State-specific details may be limited."

    return CoverageLevel.LIMITED, "Verified curated source coverage is currently limited for this jurisdiction."


def get_terminology_explanations(question: str, legal_category: LegalCategory) -> List[TerminologyExplanation]:
    """Extract relevant legal terminology explanations from the question."""
    return analyze_question_unified(question, legal_category=legal_category).terminology_explanations


def classify_request_type(question: str) -> RequestType:
    return analyze_question_unified(question).request_type


def classify_legal_category(question: str) -> LegalCategory:
    return analyze_question_unified(question).legal_category


def detect_jurisdiction(question: str, context: Optional[str] = None) -> Jurisdiction:
    return analyze_question_unified(question, context).jurisdiction


def assess_risk_level(question: str, request_type: RequestType, legal_category: LegalCategory) -> RiskLevel:
    # Use unified analysis for consistency
    analysis = analyze_question_unified(question)
    # Override with provided request_type and legal_category if they differ
    if analysis.request_type != request_type or analysis.legal_category != legal_category:
        # Fall back to original logic for exact backward compat
        question_lower = question.lower()
        for keyword in HIGH_RISK_KEYWORDS[RiskLevel.CRITICAL]:
            if keyword in question_lower:
                return RiskLevel.CRITICAL
        for keyword in HIGH_RISK_KEYWORDS[RiskLevel.HIGH]:
            if keyword in question_lower:
                return RiskLevel.HIGH
        for keyword in HIGH_RISK_KEYWORDS[RiskLevel.MEDIUM]:
            if keyword in question_lower:
                return RiskLevel.MEDIUM
        if legal_category in [LegalCategory.CRIMINAL, LegalCategory.IMMIGRATION]:
            return RiskLevel.HIGH
        if legal_category == LegalCategory.FAMILY and request_type in [RequestType.DEADLINE_INQUIRY, RequestType.ESCALATION_NEEDED]:
            return RiskLevel.HIGH
        return RiskLevel.LOW
    return analysis.risk_level


def retrieve_sources(question: str, jurisdiction: Jurisdiction, legal_category: LegalCategory) -> List[Source]:
    return analyze_question_unified(question, jurisdiction_hint=jurisdiction).sources


def generate_clarification_questions(
    question: str,
    request_type: RequestType,
    legal_category: LegalCategory,
    jurisdiction: Jurisdiction
) -> List[ClarificationQuestion]:
    return analyze_question_unified(question).clarification_questions


def analyze_question_quality(question: str, legal_category: LegalCategory, jurisdiction: Jurisdiction) -> QuestionQuality:
    return analyze_question_unified(question, jurisdiction_hint=jurisdiction).quality


def assess_information_coverage(
    question: str,
    jurisdiction: Jurisdiction,
    sources: List[Source],
    legal_category: LegalCategory
) -> tuple[CoverageLevel, str]:
    return analyze_question_unified(question, jurisdiction_hint=jurisdiction).information_coverage, \
           analyze_question_unified(question, jurisdiction_hint=jurisdiction).coverage_reason


def get_document_checklist(legal_category: LegalCategory) -> List[DocumentChecklistItem]:
    return analyze_question_unified("", legal_category=legal_category).document_checklist


def get_follow_up_suggestions(legal_category: LegalCategory, jurisdiction: Jurisdiction) -> List[FollowUpSuggestion]:
    return analyze_question_unified("", legal_category=legal_category).follow_up_suggestions


def get_terminology_explanations(question: str, legal_category: LegalCategory) -> List[TerminologyExplanation]:
    return analyze_question_unified(question, legal_category=legal_category).terminology_explanations


def build_ai_prompt(
    question: str,
    request_type: RequestType,
    risk_level: RiskLevel,
    legal_category: LegalCategory,
    jurisdiction: Jurisdiction,
    sources: List[Source],
    clarification_questions: List[ClarificationQuestion],
    context: Optional[str] = None
) -> str:
    source_text = "\n".join([
        f"- {s.title} ({s.citation or 'no citation'}) [{s.jurisdiction.value}]" 
        for s in sources
    ]) if sources else "No verified sources available for this query."
    
    clarification_text = "\n".join([
        f"- {q.question}" for q in clarification_questions
    ]) if clarification_questions else "No clarification needed."
    
    risk_guidance = {
        RiskLevel.CRITICAL: "This appears to be an urgent, high-stakes situation. Emphasize immediate professional legal help. Do not provide definitive procedural advice.",
        RiskLevel.HIGH: "This involves significant legal consequences. Strongly encourage consulting an attorney. Be clear about uncertainty.",
        RiskLevel.MEDIUM: "This has meaningful legal implications. Recommend professional consultation. Provide general information with caveats.",
        RiskLevel.LOW: "This is a general legal information request. Provide clear, helpful information with standard disclaimers."
    }[risk_level]
    
    return f"""You are a legal information assistant. Your role is to provide accurate, plain-language legal information with appropriate caveats.

USER QUESTION: {question}
CONTEXT: {context or 'None provided'}
REQUEST TYPE: {request_type.value}
RISK LEVEL: {risk_level.value}
LEGAL CATEGORY: {legal_category.value}
JURISDICTION: {jurisdiction.value}

VERIFIED SOURCES AVAILABLE:
{source_text}

CLARIFICATION QUESTIONS (if any):
{clarification_text}

RISK-SPECIFIC GUIDANCE:
{risk_guidance}

INSTRUCTIONS:
1. Provide a clear, structured response in plain language
2. Distinguish between: user-provided facts, general legal information, source-backed information, AI-generated explanation, and uncertainties
3. Never fabricate laws, cases, statutes, citations, or sources
4. If verified sources are unavailable, explicitly state this
5. For high-risk situations, emphasize professional legal consultation
6. Include practical next steps appropriate to the risk level
7. Be honest about limitations and uncertainty
8. Do not make legal conclusions or predictions about outcomes

RESPONSE FORMAT (JSON):
{{
  "summary": "2-3 sentence plain-language summary",
  "explanation": "Detailed explanation with clear sections",
  "next_steps": ["step 1", "step 2", "step 3"],
  "escalation_guidance": "Specific guidance for high-risk situations or null",
  "uncertainty_notes": ["note 1", "note 2"]
}}"""