import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Dict, List, Optional, Set
from urllib.parse import urlparse

from app.models.schemas import (
    Jurisdiction, SourceType, Source, LegalCategory, RiskLevel,
    RequestType, ClarificationQuestion
)

logger = logging.getLogger(__name__)


# Source database (in production, this would connect to a real legal database)
VERIFIED_SOURCES = {
    Jurisdiction.US_FEDERAL: [
        Source(
            type=SourceType.STATUTE,
            title="Fair Housing Act",
            citation="42 U.S.C. §§ 3601-3619",
            url="https://www.justice.gov/crt/fair-housing-act-1",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
        Source(
            type=SourceType.STATUTE,
            title="Family and Medical Leave Act",
            citation="29 U.S.C. §§ 2601-2654",
            url="https://www.dol.gov/agencies/whd/fmla",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
        Source(
            type=SourceType.STATUTE,
            title="Americans with Disabilities Act",
            citation="42 U.S.C. §§ 12101-12213",
            url="https://www.ada.gov/",
            jurisdiction=Jurisdiction.US_FEDERAL,
            verified=True
        ),
    ],
    Jurisdiction.US_CA: [
        Source(
            type=SourceType.STATUTE,
            title="California Tenant Protection Act",
            citation="Cal. Civ. Code §§ 1946.2, 1947.12",
            url="https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CIV&division=3.&title=5.&part=4.&chapter=2.&article=2.",
            jurisdiction=Jurisdiction.US_CA,
            verified=True
        ),
        Source(
            type=SourceType.GOVERNMENT_PUBLICATION,
            title="California Courts Self-Help Guide",
            url="https://selfhelp.courts.ca.gov/",
            jurisdiction=Jurisdiction.US_CA,
            verified=True
        ),
    ],
}


DISCLAIMER = (
    "This platform provides general legal information only and does not constitute legal advice. "
    "The information provided is generated by AI and may contain inaccuracies. "
    "For legal matters that could significantly affect your rights, liberty, or finances, "
    "please consult with a qualified attorney licensed in your jurisdiction. "
    "No attorney-client relationship is created by using this service."
)


# High-risk keywords that trigger escalation
HIGH_RISK_KEYWORDS = {
    RiskLevel.CRITICAL: [
        "arrest", "detention", "deportation", "eviction notice", "foreclosure",
        "domestic violence", "restraining order", "child custody emergency",
        "suicide", "self-harm", "imminent danger", "warrant", "subpoena",
        "court date tomorrow", "deadline today", "deadline tomorrow"
    ],
    RiskLevel.HIGH: [
        "lawsuit", "criminal charge", "divorce", "custody battle",
        "discrimination", "harassment", "wrongful termination",
        "medical malpractice", "personal injury", "statute of limitations",
        "immigration court", "asylum", "visa denial"
    ],
    RiskLevel.MEDIUM: [
        "contract dispute", "landlord tenant", "wage theft", "overtime",
        "unemployment benefits", "social security denial", "medicaid",
        "special education", "IEP", "consumer fraud", "debt collection"
    ]
}


# Request type classification patterns
REQUEST_TYPE_PATTERNS = {
    RequestType.DEADLINE_INQUIRY: [
        r"deadline", r"statute of limitations", r"time limit", r"how long do i have",
        r"when must i", r"filing deadline", r"appeal deadline"
    ],
    RequestType.PROCEDURAL_GUIDANCE: [
        r"how do i file", r"how to file", r"steps to", r"process for",
        r"procedure to", r"what forms", r"where do i file"
    ],
    RequestType.RIGHTS_EXPLANATION: [
        r"what are my rights", r"am i entitled", r"do i have a right",
        r"what protections", r"legal rights", r"employee rights", r"tenant rights"
    ],
    RequestType.FORM_ASSISTANCE: [
        r"fill out", r"complete the form", r"form ", r"application for",
        r"petition for", r"motion for"
    ],
    RequestType.DOCUMENT_REVIEW: [
        r"review this", r"look at this document", r"analyze this",
        r"what does this mean", r"interpret this"
    ],
}


# Legal category patterns
LEGAL_CATEGORY_PATTERNS = {
    LegalCategory.HOUSING: [
        r"eviction", r"landlord", r"tenant", r"rent", r"lease", r"housing",
        r"foreclosure", r"mortgage", r"habitability", r"security deposit"
    ],
    LegalCategory.EMPLOYMENT: [
        r"employer", r"employee", r"workplace", r"fired", r"terminated",
        r"discrimination", r"harassment", r"wage", r"overtime", r"unemployment",
        r"workers compensation", r"FMLA", r"ADA", r"wrongful termination"
    ],
    LegalCategory.FAMILY: [
        r"divorce", r"custody", r"child support", r"alimony", r"spousal support",
        r"adoption", r"guardianship", r"domestic violence", r"restraining order",
        r"paternity", r"visitation"
    ],
    LegalCategory.CRIMINAL: [
        r"arrest", r"charge", r"criminal", r"misdemeanor", r"felony",
        r"DUI", r"DWI", r"probation", r"parole", r"public defender",
        r"miranda", r"search warrant", r"indictment"
    ],
    LegalCategory.IMMIGRATION: [
        r"immigration", r"visa", r"green card", r"citizenship", r"asylum",
        r"deportation", r"removal", r"ICE", r"USCIS", r"DACA", r"TPS"
    ],
    LegalCategory.CONSUMER: [
        r"consumer", r"fraud", r"scam", r"debt collection", r"credit report",
        r"identity theft", r"warranty", r"lemon law", r"false advertising"
    ],
    LegalCategory.CIVIL_RIGHTS: [
        r"civil rights", r"discrimination", r"police misconduct", r"excessive force",
        r"voting rights", r"ADA", r"disability rights", r"housing discrimination"
    ],
    LegalCategory.HEALTHCARE: [
        r"medical", r"healthcare", r"insurance", r"medicaid", r"medicare",
        r"HIPAA", r"medical malpractice", r"informed consent", r"patient rights"
    ],
    LegalCategory.EDUCATION: [
        r"education", r"school", r"IEP", r"special education", r"504 plan",
        r"student rights", r"discipline", r"expulsion", r"Title IX"
    ],
    LegalCategory.FINANCIAL: [
        r"bankruptcy", r"debt", r"credit", r"loan", r"foreclosure",
        r"repossession", r"garnishment", r"tax", r"IRS"
    ],
}


# Jurisdiction detection patterns
JURISDICTION_PATTERNS = {
    Jurisdiction.US_CA: [r"california", r"\bca\b", r"cal\."],
    Jurisdiction.US_NY: [r"new york", r"\bny\b", r"n\.y\."],
    Jurisdiction.US_TX: [r"texas", r"\btx\b", r"tx\."],
    Jurisdiction.UK: [r"united kingdom", r"\buk\b", r"england", r"wales", r"scotland"],
    Jurisdiction.CA_FEDERAL: [r"canada", r"federal canada"],
    Jurisdiction.CA_ON: [r"ontario", r"\bon\b", r"on\."],
    Jurisdiction.AU_FEDERAL: [r"australia", r"commonwealth"],
    Jurisdiction.EU: [r"european union", r"\beu\b", r"gdpr"],
}


import re
from typing import List, Dict, Any, Optional
from datetime import datetime


def classify_request_type(question: str) -> RequestType:
    question_lower = question.lower()
    for req_type, patterns in REQUEST_TYPE_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, question_lower):
                return req_type
    return RequestType.GENERAL_INFO


def classify_legal_category(question: str) -> LegalCategory:
    question_lower = question.lower()
    scores = {}
    for category, patterns in LEGAL_CATEGORY_PATTERNS.items():
        score = sum(1 for pattern in patterns if re.search(pattern, question_lower))
        if score > 0:
            scores[category] = score
    if scores:
        return max(scores, key=scores.get)
    return LegalCategory.OTHER


def detect_jurisdiction(question: str, context: Optional[str] = None) -> Jurisdiction:
    text = (question + " " + (context or "")).lower()
    for jurisdiction, patterns in JURISDICTION_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, text):
                return jurisdiction
    return Jurisdiction.UNKNOWN


def assess_risk_level(question: str, request_type: RequestType, legal_category: LegalCategory) -> RiskLevel:
    question_lower = question.lower()
    
    # Check critical risk keywords
    for keyword in HIGH_RISK_KEYWORDS[RiskLevel.CRITICAL]:
        if keyword in question_lower:
            return RiskLevel.CRITICAL
    
    # Check high risk keywords
    for keyword in HIGH_RISK_KEYWORDS[RiskLevel.HIGH]:
        if keyword in question_lower:
            return RiskLevel.HIGH
    
    # Check medium risk keywords
    for keyword in HIGH_RISK_KEYWORDS[RiskLevel.MEDIUM]:
        if keyword in question_lower:
            return RiskLevel.MEDIUM
    
    # Certain categories inherently higher risk
    if legal_category in [LegalCategory.CRIMINAL, LegalCategory.IMMIGRATION]:
        return RiskLevel.HIGH
    if legal_category == LegalCategory.FAMILY and request_type in [RequestType.DEADLINE_INQUIRY, RequestType.ESCALATION_NEEDED]:
        return RiskLevel.HIGH
    
    return RiskLevel.LOW


def retrieve_sources(question: str, jurisdiction: Jurisdiction, legal_category: LegalCategory) -> List[Source]:
    sources = []
    
    # Add jurisdiction-specific sources
    if jurisdiction in VERIFIED_SOURCES:
        sources.extend(VERIFIED_SOURCES[jurisdiction])
    
    # Add federal sources for US jurisdictions
    if jurisdiction in [Jurisdiction.US_CA, Jurisdiction.US_NY, Jurisdiction.US_TX]:
        sources.extend(VERIFIED_SOURCES.get(Jurisdiction.US_FEDERAL, []))
    
    # Filter by relevance to legal category (simplified)
    # In production, this would use vector search / semantic matching
    return sources[:5]  # Limit to top 5


def generate_clarification_questions(
    question: str,
    request_type: RequestType,
    legal_category: LegalCategory,
    jurisdiction: Jurisdiction
) -> List[ClarificationQuestion]:
    questions = []
    
    if jurisdiction == Jurisdiction.UNKNOWN:
        questions.append(ClarificationQuestion(
            question="What is your location (state/country)? Legal information varies significantly by jurisdiction.",
            reason="Jurisdiction is required for accurate legal information",
            required=True
        ))
    
    if request_type == RequestType.DEADLINE_INQUIRY:
        questions.append(ClarificationQuestion(
            question="When did the event or incident occur? This helps determine applicable deadlines.",
            reason="Deadlines depend on specific dates",
            required=True
        ))
    
    if legal_category == LegalCategory.HOUSING and "eviction" in question.lower():
        questions.append(ClarificationQuestion(
            question="Have you received a written eviction notice? If so, what type (e.g., 3-day, 30-day)?",
            reason="Eviction procedures vary by notice type",
            required=True
        ))
    
    if legal_category == LegalCategory.EMPLOYMENT and "terminat" in question.lower():
        questions.append(ClarificationQuestion(
            question="How many employees does your employer have? This affects which laws apply.",
            reason="Employment law thresholds vary by employer size",
            required=False
        ))
    
    return questions


def build_ai_prompt(
    question: str,
    request_type: RequestType,
    risk_level: RiskLevel,
    legal_category: LegalCategory,
    jurisdiction: Jurisdiction,
    sources: List[Source],
    clarification_questions: List[ClarificationQuestion],
    context: Optional[str] = None
) -> str:
    source_text = "\n".join([
        f"- {s.title} ({s.citation or 'no citation'}) [{s.jurisdiction.value}]" 
        for s in sources
    ]) if sources else "No verified sources available for this query."
    
    clarification_text = "\n".join([
        f"- {q.question}" for q in clarification_questions
    ]) if clarification_questions else "No clarification needed."
    
    risk_guidance = {
        RiskLevel.CRITICAL: "This appears to be an urgent, high-stakes situation. Emphasize immediate professional legal help. Do not provide definitive procedural advice.",
        RiskLevel.HIGH: "This involves significant legal consequences. Strongly encourage consulting an attorney. Be clear about uncertainty.",
        RiskLevel.MEDIUM: "This has meaningful legal implications. Recommend professional consultation. Provide general information with caveats.",
        RiskLevel.LOW: "This is a general legal information request. Provide clear, helpful information with standard disclaimers."
    }[risk_level]
    
    return f"""You are a legal information assistant. Your role is to provide accurate, plain-language legal information with appropriate caveats.

USER QUESTION: {question}
CONTEXT: {context or 'None provided'}
REQUEST TYPE: {request_type.value}
RISK LEVEL: {risk_level.value}
LEGAL CATEGORY: {legal_category.value}
JURISDICTION: {jurisdiction.value}

VERIFIED SOURCES AVAILABLE:
{source_text}

CLARIFICATION QUESTIONS (if any):
{clarification_text}

RISK-SPECIFIC GUIDANCE:
{risk_guidance}

INSTRUCTIONS:
1. Provide a clear, structured response in plain language
2. Distinguish between: user-provided facts, general legal information, source-backed information, AI-generated explanation, and uncertainties
3. Never fabricate laws, cases, statutes, citations, or sources
4. If verified sources are unavailable, explicitly state this
5. For high-risk situations, emphasize professional legal consultation
6. Include practical next steps appropriate to the risk level
7. Be honest about limitations and uncertainty
8. Do not make legal conclusions or predictions about outcomes

RESPONSE FORMAT (JSON):
{{
  "summary": "2-3 sentence plain-language summary",
  "explanation": "Detailed explanation with clear sections",
  "next_steps": ["step 1", "step 2", "step 3"],
  "escalation_guidance": "Specific guidance for high-risk situations or null",
  "uncertainty_notes": ["note 1", "note 2"]
}}"""